### ISSUE TITLE
add reference to hubAdmin::create_config() in quickstart

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubDocs#100]
It would be good to point users to this tool to help with configuration
https://hubdocs.readthedocs.io/en/latest/quickstart-hub-admin/tasks-config.html

**Comment by micokoch** [comment]
I went through the functions in `hubAdmin`, and it wasn't clear to me how I would integrate this into the quickstart. Not much is explained in the [package page](https://infectious-disease-modeling-hubs.github.io/hubAdmin/reference/index.html), and when going through the function help page, `create_config` requires one to create a round first.

So, my questions are: where in the quickstart would I point users to these tools, and what should I point to?

**Comment by nickreich** [comment]
Answering the above questions:

1. I think we could add a new quickstart page after "Configuring tasks" that is called something like "Scripting task configuration" or something like that.
1. The best solution here would be to create a full example where we have a script that is used to create a round and a task etc... The [example here](https://infectious-disease-modeling-hubs.github.io/hubAdmin/reference/create_rounds.html#ref-examples) might be a useful starting point as example code to base things off of?

Happy to discuss more!
