### ISSUE TITLE
remove static storage of hubensembles vignette

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubDocs#139]
At the very bottom of the left menu on the hubverse.io documentation site there is a link to the hubEnsembles vignette at this page: https://hubverse.io/en/latest/more-info/hubEnsembles-vignette.html

This seems like an inefficient way of storing this vignette. Why are we storing this here and not just linking to the hubEnsembles pkgdown site? I note that hubEnsembles does not have a vignette as part of the package yet (I think one is coming very soon). @lshandross maybe you have more insight about this?

**Comment by lshandross** [comment]
There is a vignette for the package that you can access using the [Get Started link](https://hubverse-org.github.io/hubEnsembles/articles/hubEnsembles.html) on the pkgdown site. I think that it's listed there instead of under the usual Articles menu because the file name is the same as the package name

**Comment by micokoch** [comment]
I don't remember the details, but at some point I was asked to include [an example workflow which Lucie had built](https://github.com/hubverse-org/example-complex-scenario-hub/tree/main/articles) in [the hubDocs site](https://hubverse.io/en/latest/quickstart-hub-admin/using-hub.html#building-ensembles). I tried various ways of including it in the site (trying to insert the R Markdown file directly for instance), but ultimately couldn't find a better way than the way it is now. It is easy enough to remove it and link to the Get Started link Li suggested, but first I want to verify that is what you want. Put more clearly:

1. Should I delete the HubEnsembles vignette page from the hubDocs site? An alternative is to move to the User Guide folder.
2. Should [the link to the vignette here](https://hubverse.io/en/latest/quickstart-hub-admin/using-hub.html#building-ensembles) link to the [Get Started link](https://hubverse-org.github.io/hubEnsembles/articles/hubEnsembles.html) instead?

Let me know and I can work on this.

**Comment by lshandross** [comment]
Alvaro added some updated information above but here's my extended reply to Nick's original comment: 
> Also, I'm realizing that the "hubEnsembles vignette" linked on the page Nick is referencing is actually more of a general demonstration for loading a local hub using `hubData`, ensembling with `hubEnsembles`, and plotting with `hubVis`, which Lucie made. It's also linked at the bottom of the [Using the Modeling Hub page](https://hubverse.io/en/latest/quickstart-hub-admin/using-hub.html). I think that we should also update this link to either go to where that general vignette lives on the `hubData` pkgdown site or to the vignette I wrote in the `hubverse` package (which is the same thing but for cloud data retrieval instead of local). I don't know if we want to like the vignettes specific to `hubEnsembles` only.

**Comment by nickreich** [comment]
@LucieContamin can you comment on the purpose of this file? 

Unless I hear a good argument otherwise, I think we should remove the "Hubensembles vignette" from the documentation site and delete the link entirely, i.e. not repoint the link to some other existing resource.

**Comment by LucieContamin** [comment]
If I remember correctly, I think the goal was to have a simple vignette showing how to use the main functions especially the ensemble, in a simple workflow. But, I don't think it matches anymore. I mean we have more complete and complex example. I think it's also misleading to call it hubensemble as it's not a vignette associated with the hubEnsembles package. So I think it will be a good idea to remove that one and instead link to the more up to date and complete vignettes available in the different hubverse packages

**Comment by nickreich** [comment]
Great - thanks for the comment @LucieContamin ! I agree and think we should remove this file and the link from the main hubverse website.

**Comment by micokoch** [comment]
I removed the file and the link in PR #158 . Once approved and merged, I will close this issue.
