### ISSUE TITLE
Add list of hubverse hubs to documentation site

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubDocs#149]
There are many ways to do this, but the content from [this doc](https://docs.google.com/document/d/1jVb58Cert1ON-Do1TdwBxpeiFHMkjqDLofgV2oqezOo/edit) needs to be added to the website. In particular, just the "active hubs using hubverse" should be added. Ideally there would be a list with some standard way of representing the data. Perhaps just the "name" of the hub, a brief description and a link to the repo and/or website for each one?

My suggestion might be to make this its own page under the "Overview" section, but I don't feel strongly about that. I'm not sure what the title should be "List of hubs"?

**Comment by zkamvar** [comment]
I think it might be a good idea to list these hubs in a section directly on the landing page. This would really help answer the question of "What does a modelling hub in the hubverse look like?" The name of the hub plus any links as icons should be good.

**Comment by micokoch** [comment]
Once this is done, should it replace or complement the list that is here?
https://hubverse.io/en/latest/overview/who-we-are.html

**Comment by nickreich** [comment]
I like @zkamvar's idea to list them on the landing page. 

@micokoch : also a good question. That list is a list of hubs that adapted the original covid-19 hub architecture, not of current hubverse hubs. I think it is helpful, for historical reasons, to include that list, but we could list them less prominently, e.g. we could say something like "This infrastructure was later adapted for use by several other modeling hubs in the US[1] and Europe[2]." and then have sidenotes with the names/links of the hubs, so it's not such an attraction-seeking list?

There are probably other, maybe better ways of doing this, but this is just one idea.
