### ISSUE TITLE
Example workflow has git merge artifacts

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubDocs#150]
There are several git merge artifacts in the example workflow. I would attempt to re-render, but I cannot find the source file for it. 

https://github.com/hubverse-org/hubDocs/blob/0bee761c4b28f732bc350515f72c9d5dc85fd0ab/docs/_static/example_workflow.html#L377-L390

**Comment by micokoch** [comment]
Hi, thanks for looking into this. Here are the source files:
https://github.com/hubverse-org/example-complex-scenario-hub/tree/main/articles

**Comment by micokoch** [comment]
I assigned you @zkamvar, but let me know if you need any more information. Thanks!

**Comment by zkamvar** [comment]
From what I understand on [lines 69 through 81](https://github.com/hubverse-org/example-complex-scenario-hub/blob/2e8138fd2bc6eec8005b76e23d277fb66b66451a/articles/example_workflow.Rmd#L69-L81), this should be run in the root of https://github.com/hubverse-org/example-complex-scenario-hub/tree/main?

**Comment by micokoch** [comment]
I'm not sure. @LucieContamin do you know the answer to this question?

**Comment by LucieContamin** [comment]
Hmm I could not find it in the last version of the file, but just in case I regenerate it (all file format: Rmd, HTML and PDF) so please feel free to use the last version, it should fix the problem
