### ISSUE TITLE
replace uninformative link text with descriptive text

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubDocs#166]
There are several places within the documentation that have [uninformative link text](https://webaim.org/techniques/hypertext/link_text#uninformative) (i.e. places where the link says "here", "this table", "this page", etc.)

This is inaccessible design for users of screen reader software and it is recommended to update the phrasing to have more descriptive link text. Effectively, if you take the link text out of context, would you be able to guess where the link goes? 

Here are some examples from the help documentation:

* If you do not have a GitHub account, create one following [these instructions](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account) (a free account is fine).
* A detailed description of the `model-metadata` directory can be found [here](https://hubverse.io/en/latest/user-guide/model-metadata.html).

Here is how they could be rewritten:

* If you do not have a GitHub account, create one by following [the official GitHub instructions for getting started](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account) (a free account is fine).
* [The model metadata chapter](https://hubverse.io/en/latest/user-guide/model-metadata.html) gives a detailed description of the `model-metadata` directory.

I've found searching for "examples of descriptive links" helpful in getting a general sense of the guidelines for appropriate link text.

**Comment by micokoch** [comment]
This may have auto-closed because I linked it to #186, but I still have other sections to review - so I'm re-opening this issue.
