### ISSUE TITLE
describe what the directories are for in the Structure of Hub Repositories

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubDocs#167]
At the moment, the directory structure is a list of directories with links out to individual pages, but summary of what the folders are actually for (with the exception of the `src` directory). 

> hub-config directory (see Hub configuration files)
> model-output directory (see Model output)
> model-metadata directory (see Model metadata)
> model-abstracts directory (optional, see Model abstracts)
> target-data directory (optional, see Target data)
> auxiliary-data directory (optional, see Target data)
> src directory (optional, for code that is present in the hub repository)

If we could add a one-sentence summary of each folder, it would aid in understanding.

**Comment by lshandross** [comment]
Just to confirm, can this issue be closed given that it was addressed in the above pull request (#170), which has been merged into main?

**Comment by mmkerr** [comment]
Yes, sorry. I'll close it now

**Comment by zkamvar** [comment]
Thank you for the fix, @mmkerr!
