### ISSUE TITLE
Add documentation about `derived_task_ids` property

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubDocs#193]
When updating to  `v4.0.0` add short section about derived taks IDs

Could be a rephrasing of the NEWS entry in schema:

> Introduction of optional `derived_task_ids` properties to enable hub administrators to define derived task IDs (i.e. task IDs whose values depend on the values of other task IDs). The higher level `derived_task_ids` property sets the property globally at the hub level but can be overriden by the round level `derived_task_ids` property. The property allows for primarily validation functionality to ignore such task IDs when appropriate which can significantly improve validation efficency (#96). For more information see [`hubValidations` documentation on ignoring derived task IDs](https://hubverse-org.github.io/hubValidations/articles/validate-pr.html#ignoring-derived-task-ids-to-improve-performance).

**Comment by zkamvar** [comment]
I think this would actually help out with #208 because the language used to describe what task id variables are needed for generating the oracle output data is a bit dense:

> - The oracle output should include enough of the task id variables and
>   columns with metadata about the outputs (`output_type` and
>   `output_type_id`) to uniquely identify which `oracle_value`s
>   correspond to which predicted `value`s. For example, this will
>   typically include task id variables such as `location` and
>   `target_date` (or `target_end_date`), since the `oracle_value` will be
>   specific to the `location` and `target_date`.
> - Any task id variables that are not necessary to match observations
>   with predictions can be omitted from the oracle output. For example,
>   if `target_date` is included then `reference_date` and `horizon`
>   variables can be omitted because the same observation will generally
>   correspond to a particular `target_date` regardless of the forecast
>   horizon. Similarly, in a scenario projection setting, the
>   `scenario_id` can be omitted.
>

**Comment by zkamvar** [comment]
From [my search of GitHub for derived_task_ids in validate_pr](https://github.com/search?q=path%3A.github%2Fworkflows%2F+%28derived_task_ids+AND+validate_pr%29&type=code), it looks like we only have to notify @M-7th that the hub- and round-level `derived_task_ids` property will be available for schemas v4 so that you don't have to manually set those in the validation workflow.

**Comment by annakrystalli** [comment]
We should also this in quick start and show an example of setting the `derived_task_ids` property in the config
