### ISSUE TITLE
Update documentation on output type id changes in v4.0.0

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubDocs#194]
- Remove any mention of `optional` property in output type IDs and explain that there no optional output type ID values anymore, only optional output typess.
- Explain the `is_required` property

**Comment by zkamvar** [comment]
Files to change:

 - `docs/source/quickstart/tasks-config.md`
 - `docs/source/quickstart/scripting-tasks-config.md`
 - `docs/source/user-guide/hub-config.md`
 - `docs/source/user-guide/sample-output-type.md`

**Comment by zkamvar** [comment]
🙈 after all that discussion about not using optional and required quantiles

https://github.com/hubverse-org/hubDocs/blob/700e6cd7fae2d12ab5c802c150c31ec2fb9914af/docs/source/quickstart-hub-admin/scripting-task-config.md?plain=1#L87-L93

**Comment by annakrystalli** [comment]
Oh I never even realised this had been added to the docs! I think this should be moved to hubAdmin as an executable vignette and linked to from hubDocs. It'll be much easier to ensure its up to date that way and it'll also show results of functions.
