### ISSUE TITLE
clean up description of groups of columns in model output

### ISSUE THREAD

**Issue by elray1** [hubverse-org/hubDocs#201]
Looking at this page: https://hubverse.io/en/latest/user-guide/model-output.html#model-output-format

Screenshot of specific text block:
![image](https://github.com/user-attachments/assets/f0528d24-91a5-445b-8be3-04a402b10805)

Comments:

- I believe the intent here was probably to nest points 3 through 5 as a sublist under point 2, but they ended up as items at the same outer list level.
- However, I'd suggest updating this as follows:

2. "Model output representation" (2 columns): consists of two columns specifying how the model outputs are represented. Both of these columns will be present in all model output data:
    1. `output_type` ...
    2. `output_type_id` ...
3. `value` contains the model's prediction.

The rationale here is that `output_type` and `output_type_id` specify how model outputs are represented, but `value` is the actual model output rather than metadata about the representation of that output.

(We've iterated on this text in a past PR, but I couldn't quickly find a link with meaningful discussion.)

**Comment by micokoch** [comment]
Hi Evan. I remember we talked about this, and I used the structure in the hubEnsembles manuscript. Anyway, I updated the structure as you suggested in PR #202.
