### ISSUE TITLE
add image to roles documentation page

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubDocs#209]
this page: https://hubverse.io/en/latest/overview/who-uses-hubverse.html

the Figure 1 image from the hubverse MS (don't use this version but this is just a screenshot)
<img width="666" alt="image" src="https://github.com/user-attachments/assets/a4ae931c-ee26-4851-9954-b9a1ae09dc97">

**Comment by micokoch** [comment]
Addressed in #214 .
